---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройства
implicit:
  - Сайт должен иметь продуманный путь пользователя — от выбора товара до оформления заказа и оплаты
  - Интерфейс должен быть интуитивно понятным и простым в навигации, чтобы пользователи могли без труда находить нужные товары и услуги
  - Сайт должен соответствовать стандартам доступности, чтобы люди с ограниченными возможностями, могли пользоваться сайтом без затруднений
  - Необходимо, чтобы пользователи были зарегистрированы в интернет-магазине используя логин, пароль, почту или номер телефона
  - Система должна предоставлять пользователям понятные сообщения об ошибках при возникновении проблем (например, при некорректном вводе данных при регистрации или входе в личный кабинет)
  - Добавлять товар в корзину и формлять заказ могут только зарегистрированные и авторизованные пользователи
  - При оформлении товара система должна использовать номер телефона или почту пользователя (введенные при регистрации) для обратной связи
  - Необходимо добавить функцию отмены оформленного(купленного) товара с возвратом денежных средств
